# .travis.yml
---

dist: trusty
sudo: required
language: python
python:
  - "2.7"
env:
  - >
    DISTRIBUTION=ubuntu
    DIST_VERSION=18_04-builded
    MONGODB_VERSION=3.6
    MONGODB_PACKAGE=mongodb
  - >
    DISTRIBUTION=ubuntu
    DIST_VERSION=16_04-builded
    MONGODB_VERSION=3.6
  - >
    DISTRIBUTION=ubuntu
    DIST_VERSION=16_04-builded
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=ubuntu
    DIST_VERSION=16_04-builded
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=ubuntu-upstart
    DIST_VERSION=14.04
    MONGODB_VERSION=3.6
  - >
    DISTRIBUTION=ubuntu-upstart
    DIST_VERSION=14.04
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=ubuntu-upstart
    DIST_VERSION=14.04
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=debian
    DIST_VERSION=9-builded
    MONGODB_VERSION=3.6
  - >
    DISTRIBUTION=debian
    DIST_VERSION=9-builded
    MONGODB_VERSION=3.2
    MONGODB_PACKAGE=mongodb
  - >
    DISTRIBUTION=debian
    DIST_VERSION=8-builded
    MONGODB_VERSION=3.6
  - >
    DISTRIBUTION=debian
    DIST_VERSION=8-builded
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=debian
    DIST_VERSION=8-builded
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=centos
    DIST_VERSION=6-builded
    MONGODB_VERSION=3.6
  - >
    DISTRIBUTION=centos
    DIST_VERSION=6-builded
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=centos
    DIST_VERSION=6-builded
    MONGODB_VERSION=3.2
  - >
    DISTRIBUTION=centos
    DIST_VERSION=7-builded
    MONGODB_VERSION=3.6
  - >
    DISTRIBUTION=centos
    DIST_VERSION=7-builded
    MONGODB_VERSION=3.4
  - >
    DISTRIBUTION=centos
    DIST_VERSION=7-builded
    MONGODB_VERSION=3.2

services:
  - docker

install:
  - bash tests/scripts/before_install.sh

script:
  - bash tests/scripts/test.sh

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
