---
- name: Replication configuration
  mongodb_replication:
    login_host: "{{ mongodb_login_host|default('localhost') }}"
    login_port: "{{ mongodb_conf_port|default(27017) }}"
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    replica_set: "{{ mongodb_conf_replSet }}"
    host_name: "{{ item.host_name }}"
    host_port: "{{ item.host_port|default(27017) }}"
    host_type: "{{ item.host_type|default('replica') }}"
    hidden: "{{ item.hidden|default(false) }}"
    priority: "{{ item.priority|default(1.0) }}"
  when: mongodb_replication_params is defined
  with_items:
    - "{{ mongodb_replication_params|default([]) }}"
  register: mongodb_replica_init
  ignore_errors: true

- include: auth_initialization.yml
  when: mongodb_replica_init|failed

- name: Replication configuration
  mongodb_replication:
    login_host: "{{ mongodb_login_host|default('localhost') }}"
    login_port: "{{ mongodb_conf_port|default(27017) }}"
    login_user: "{{ mongodb_root_admin_name }}"
    login_password: "{{ mongodb_root_admin_password }}"
    replica_set: "{{ mongodb_conf_replSet }}"
    host_name: "{{ item.host_name }}"
    host_port: "{{ item.host_port|default(27017) }}"
    host_type: "{{ item.host_type|default('replica') }}"
    hidden: "{{ item.hidden|default(false) }}"
    priority: "{{ item.priority|default(1.0) }}"
  when: mongodb_replication_params is defined
  with_items:
    - "{{ mongodb_replication_params|default([]) }}"
  when: mongodb_replica_init|failed
