---

- name: mongodb reload
  service: name={{ mongodb_daemon_name }} state=reloaded
  when: mongodb_manage_service

- name: mongodb restart
  service: name={{ mongodb_daemon_name }} state=restarted
  when: mongodb_manage_service

- name: mongodb-mms-automation-agent restart
  service: name=mongodb-mms-automation-agent state=restarted
  when: mongodb_manage_service

- name: reload systemd
  shell: systemctl daemon-reload
  when: systemd.stat.exists == true and mongodb_manage_service

- name: restart sysfsutils
  service: name=sysfsutils state=restarted
